/**
 * Nashik Kumbh Reference Stay Listings (Isolated Reference Dataset)
 * Geographic Scope: nashik
 * Data Status: reference
 * 
 * IMPORTANT: This dataset must NEVER be served on the Prayagraj pilgrim discovery portal.
 */

export const nashikReferenceProperties = [
  {
    title: 'Panchavati Heritage Pilgrim Hotel',
    description: 'A trusted heritage hotel located right in the sacred heart of Nashik Panchavati, just steps from Ramkund Ghat. AC and non-AC rooms with lift access, secure vehicle parking, and dedicated room service.',
    propertyType: 'hotel',
    address: 'Opp. Sita Gumpha, Panchavati',
    city: 'Nashik',
    state: 'Maharashtra',
    country: 'India',
    locationScope: 'nashik',
    dataStatus: 'reference',
    latitude: 20.0063,
    longitude: 73.7915,
    location: {
      type: 'Point',
      coordinates: [73.7915, 20.0063],
    },
    distanceFromKumbh: '350 m from Ramkund Ghat',
    distancePoints: [
      { pointName: 'Ramkund Sacred Snan Ghat', distance: '350 meters (4 min walk)', type: 'ghat' },
      { pointName: 'Kalaram Temple', distance: '200 meters', type: 'temple' },
      { pointName: 'Godavari Ghat Bridge', distance: '400 meters', type: 'ghat' },
      { pointName: 'Nashik Road Railway Station', distance: '8.5 km', type: 'station' },
    ],
    pricePerNight: 2400,
    priceRange: 'mid_range',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['wifi', 'ac', 'water', 'hotWater24h', 'parking', 'attachedBathroom', 'powerBackup'],
    occupantPreferences: ['family', 'bachelor', 'seniorCitizen'],
    googlePlaceId: 'ChIJ_nashik_panchavati_heritage_03',
    googleRating: 4.6,
    googleReviewCount: 230,
    googleReviews: [
      {
        author: 'Sanjay Kulkarni',
        rating: 5,
        text: 'You cannot get a closer hotel to Ramkund and Kalaram temple. Perfect location for Shahi Snan participation.',
        date: 'March 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 94,
    lastVerifiedAt: new Date('2026-08-10'),
    rules: ['Valid ID card required for all guests', 'Strictly pure vegetarian restaurant on premise'],
    contactPhone: '+91 98220 99881',
    source: { file: 'SEVAK_AI_Agentic_Volunteer_Operations_Blueprint.pdf', originalId: 'NSK_REF_001' },
    isDemo: false,
    isActive: true,
  },
  {
    title: 'Trimbakeshwar Seva Ashram Dormitory',
    description: 'A large, community-oriented seva ashram near the holy Jyotirlinga and Kushavarta Kund. Offers clean budget dorm beds, locker facilities, and community Mahaprasad twice daily.',
    propertyType: 'hostel',
    address: 'Near Kushavarta Snan Kund, Temple Road',
    city: 'Trimbakeshwar',
    state: 'Maharashtra',
    country: 'India',
    locationScope: 'nashik',
    dataStatus: 'reference',
    latitude: 19.9324,
    longitude: 73.5308,
    location: {
      type: 'Point',
      coordinates: [73.5308, 19.9324],
    },
    distanceFromKumbh: '250 m from Kushavarta Kund',
    distancePoints: [
      { pointName: 'Kushavarta Snan Kund', distance: '250 meters', type: 'ghat' },
      { pointName: 'Trimbakeshwar Jyotirlinga Temple', distance: '400 meters', type: 'temple' },
      { pointName: 'Trimbak Bus Stand', distance: '600 meters', type: 'shuttle' },
    ],
    pricePerNight: 450,
    priceRange: 'budget',
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['water', 'hotWater24h', 'pureVegFood'],
    occupantPreferences: ['bachelor', 'sadhus_pilgrims'],
    googlePlaceId: 'ChIJ_trimbak_seva_ashram_04',
    googleRating: 4.5,
    googleReviewCount: 156,
    googleReviews: [
      {
        author: 'Govind Swaroop',
        rating: 5,
        text: 'Extremely peaceful spiritual environment. Free hot drinking water and simple, nourishing satvik mahaprasad.',
        date: 'February 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 92,
    lastVerifiedAt: new Date('2026-08-18'),
    rules: ['Dorm silence after 9:30 PM', 'No smoking or tobacco allowed'],
    contactPhone: '+91 94222 33445',
    source: { file: 'SEVAK_AI_Agentic_Volunteer_Operations_Blueprint.pdf', originalId: 'NSK_REF_002' },
    isDemo: false,
    isActive: true,
  },
  {
    title: 'Godavari Comforts Homestay',
    description: 'A clean 2-bedroom homestay apartment in Gangapur Road, Nashik. Excellent for family groups traveling with cars, with secure private parking and full kitchen access for preparing personal baby/elderly food.',
    propertyType: 'homestay',
    address: 'Near Old Gangapur Naka, Gangapur Road',
    city: 'Nashik',
    state: 'Maharashtra',
    country: 'India',
    locationScope: 'nashik',
    dataStatus: 'reference',
    latitude: 20.0125,
    longitude: 73.7742,
    location: {
      type: 'Point',
      coordinates: [73.7742, 20.0125],
    },
    distanceFromKumbh: '1.8 km from Ramkund Ghat',
    distancePoints: [
      { pointName: 'Ramkund Ghat', distance: '1.8 km (7 min drive / direct bus)', type: 'ghat' },
      { pointName: 'CBS Bus Terminal', distance: '1.5 km', type: 'shuttle' },
    ],
    pricePerNight: 1600,
    priceRange: 'mid_range',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['wifi', 'ac', 'water', 'hotWater24h', 'parking', 'attachedBathroom', 'pureVegFood'],
    occupantPreferences: ['family', 'children', 'seniorCitizen'],
    googlePlaceId: 'ChIJ_nashik_godavari_comforts_08',
    googleRating: 4.7,
    googleReviewCount: 64,
    googleReviews: [
      {
        author: 'Meenakshi Deshmukh',
        rating: 5,
        text: 'The host was extremely supportive. We were able to cook khichdi for our small toddler.',
        date: 'February 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 96,
    lastVerifiedAt: new Date('2026-08-12'),
    rules: ['Family guests preferred', 'No loud music'],
    contactPhone: '+91 98230 44556',
    source: { file: 'SEVAK_AI_Agentic_Volunteer_Operations_Blueprint.pdf', originalId: 'NSK_REF_003' },
    isDemo: false,
    isActive: true,
  },
];
