/**
 * Prayagraj Healthcare and First Aid Assistance Points (Demo Dataset)
 * Geographic Scope: prayagraj
 * Data Status: demo
 */

export const prayagrajMedicalPoints = [
  {
    name: 'Sangam Sector 2 Red Cross Emergency Hospital',
    type: 'Hospital',
    address: 'Near Pontoon Bridge 2, Sector 2 Mela Enclave',
    city: 'Prayagraj',
    sector: 'Sector 2 (Sangam Enclave)',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4340,
    longitude: 81.8650,
    location: { type: 'Point', coordinates: [81.8650, 25.4340] },
    phone: '108',
    services: ['24/7 Oxygen Supply', 'ICU Emergency Beds', 'Trauma Care Unit', 'Doctor Consultation', 'Free Essential Medicines', 'Ambulance Bay'],
    operatingHours: '24 Hours Open (Continuous Emergency Shift)',
    isEmergency: true,
    hasAmbulanceBay: true,
    isActive: true,
    isDemo: true,
  },
  {
    name: 'Daraganj Ghat Medical Booth No. 3',
    type: 'Medical Booth',
    address: 'Plot 12, Daraganj Ghat Marg, near Sector 2 Entry Gate',
    city: 'Prayagraj',
    sector: 'Sector 2',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4315,
    longitude: 81.8690,
    location: { type: 'Point', coordinates: [81.8690, 25.4315] },
    phone: '108',
    services: ['First Aid & Dressing', 'Doctor on Duty', 'Free ORS & Hydration', 'Blood Pressure & Sugar Check', 'General Medicines'],
    operatingHours: '24 Hours Open',
    isEmergency: true,
    hasAmbulanceBay: false,
    isActive: true,
    isDemo: true,
  },
  {
    name: 'Sector 4 Central Yatri Ambulance Point',
    type: 'Ambulance Point',
    address: 'Sector 4 Parking & Shuttle Terminal Hub',
    city: 'Prayagraj',
    sector: 'Sector 4',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4410,
    longitude: 81.8590,
    location: { type: 'Point', coordinates: [81.8590, 25.4410] },
    phone: '108',
    services: ['Rapid Ambulance Evacuation', 'Paramedic First Response', 'Oxygen Support', 'Stretcher & Wheelchair Service'],
    operatingHours: '24 Hours Open',
    isEmergency: true,
    hasAmbulanceBay: true,
    isActive: true,
    isDemo: true,
  },
  {
    name: 'Alopibagh Pilgrim First Aid Camp',
    type: 'First Aid',
    address: '14/B, Alopi Devi Temple Marg, Alopibagh',
    city: 'Prayagraj',
    sector: 'Alopibagh / Sector 5',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4398,
    longitude: 81.8741,
    location: { type: 'Point', coordinates: [81.8741, 25.4398] },
    phone: '108',
    services: ['Wound Dressing', 'Foot Blister Care', 'Free ORS', 'Senior Citizen Health Check'],
    operatingHours: '6:00 AM - 11:00 PM',
    isEmergency: false,
    hasAmbulanceBay: false,
    isActive: true,
    isDemo: true,
  },
];
