/**
 * Prayagraj Kumbh Stay Listings (Demo & Production Seed Dataset)
 * Geographic Scope: prayagraj
 * Data Status: demo
 */

export const prayagrajProperties = [
  {
    title: 'Shree Ram Residency & Pilgrim Niwas',
    description: 'A dedicated pilgrim guest house located within walking distance of the Sangam Triveni Ghat. Features spacious family rooms, clean Western and Indian attached washrooms, and 24/7 solar-geyser hot water. Sattvic pure vegetarian breakfast and herbal tea provided every morning for yatris.',
    propertyType: 'hotel',
    address: 'Plot 14, Daraganj Ghat Marg, Sector 2',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    country: 'India',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4312,
    longitude: 81.8682,
    location: {
      type: 'Point',
      coordinates: [81.8682, 25.4312],
    },
    distanceFromKumbh: '800 m from Sangam Triveni Ghat',
    distancePoints: [
      { pointName: 'Sangam Triveni Snan Ghat', distance: '800 meters (10 min walk)', type: 'ghat' },
      { pointName: 'Pontoon Bridge No. 3', distance: '400 meters', type: 'ghat' },
      { pointName: 'Sector 2 Electric Shuttle Stand', distance: '150 meters', type: 'shuttle' },
      { pointName: 'Temporary Mela First Aid Post', distance: '200 meters', type: 'medical' },
      { pointName: 'Prayagraj Rambag Railway Station', distance: '2.5 km', type: 'station' },
    ],
    pricePerNight: 850,
    priceRange: 'budget',
    images: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['wifi', 'water', 'hotWater24h', 'attachedBathroom', 'pureVegFood', 'powerBackup'],
    occupantPreferences: ['family', 'female', 'children', 'seniorCitizen'],
    googlePlaceId: 'ChIJ_prayagraj_ram_residency_01',
    googleRating: 4.4,
    googleReviewCount: 184,
    googleReviews: [
      {
        author: 'Rameshwar Dayal',
        rating: 5,
        text: 'Clean bedding and genuinely 24/7 hot water even at 4 AM before the holy snan. The walking path to Sangam Ghat was very safe and well lit.',
        date: 'February 2026',
      },
      {
        author: 'Sunita Mehra',
        rating: 4,
        text: 'Very comfortable stay for our family with elderly parents. Ground floor rooms available with zero stairs. Staff is polite and helpful.',
        date: 'January 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 95,
    lastVerifiedAt: new Date('2026-08-15'),
    rules: ['Sattvic pure vegetarian food only', '24h Hot water available for snan', 'Quiet hours after 10 PM'],
    contactPhone: '+91 98200 11223',
    source: { file: 'prayagraj_verified_directory.json', originalId: 'PRY_001' },
    isDemo: true,
    isActive: true,
  },
  {
    title: 'Ananda Ganga Homestay & Satsang Niwas',
    description: 'A warm and peaceful family homestay hosted by a local teacher family in Alopibagh. Offers clean rooms, authentic sattvic home meals, luggage safekeeping, and personalized assistance for Kalpvasi pilgrims.',
    propertyType: 'homestay',
    address: '12/A, Alopibagh Road, near Alopi Devi Temple',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    country: 'India',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4398,
    longitude: 81.8741,
    location: {
      type: 'Point',
      coordinates: [81.8741, 25.4398],
    },
    distanceFromKumbh: '1.2 km from Sangam Area',
    distancePoints: [
      { pointName: 'Alopi Devi Mandir', distance: '150 meters', type: 'temple' },
      { pointName: 'Sangam Snan Ghat', distance: '1.2 km (E-rickshaw available)', type: 'ghat' },
      { pointName: 'Mela Sector 4 Entry Gate', distance: '600 meters', type: 'shuttle' },
    ],
    pricePerNight: 1200,
    priceRange: 'budget',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['wifi', 'water', 'hotWater24h', 'attachedBathroom', 'pureVegFood'],
    occupantPreferences: ['family', 'female', 'seniorCitizen'],
    googlePlaceId: 'ChIJ_prayagraj_ananda_ganga_02',
    googleRating: 4.8,
    googleReviewCount: 92,
    googleReviews: [
      {
        author: 'Pooja Agarwal',
        rating: 5,
        text: 'The host family treated us like divine guests. The food was strictly satvik and very fresh. Highly recommend for female travelers.',
        date: 'January 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 97,
    lastVerifiedAt: new Date('2026-08-20'),
    rules: ['No non-veg or alcohol allowed', 'Shoes off at entrance', 'Check-in 12 PM'],
    contactPhone: '+91 94150 55667',
    source: { file: 'prayagraj_verified_directory.json', originalId: 'PRY_002' },
    isDemo: true,
    isActive: true,
  },
  {
    title: 'Sangam View Luxury Tented Colony',
    description: 'Premium Swiss cottage tents situated right inside the authorized Kumbh Mela luxury sector. Includes air conditioning, attached tiled washrooms with geysers, complimentary sattvic buffet meals, and VIP Snan escort pass assistance.',
    propertyType: 'tent',
    address: 'Sector 1 VIP Enclave, Sangam Marg',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    country: 'India',
    locationScope: 'prayagraj',
    dataStatus: 'demo',
    latitude: 25.4285,
    longitude: 81.8763,
    location: {
      type: 'Point',
      coordinates: [81.8763, 25.4285],
    },
    distanceFromKumbh: '200 m from VIP Snan Ghat',
    distancePoints: [
      { pointName: 'Sangam VIP Ghat', distance: '200 meters', type: 'ghat' },
      { pointName: 'Akshayavat Temple', distance: '500 meters', type: 'temple' },
      { pointName: 'Helipad / VIP Shuttle Drop', distance: '300 meters', type: 'shuttle' },
    ],
    pricePerNight: 3500,
    priceRange: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['wifi', 'ac', 'water', 'hotWater24h', 'parking', 'attachedBathroom', 'pureVegFood', 'powerBackup'],
    occupantPreferences: ['family', 'seniorCitizen'],
    googlePlaceId: 'ChIJ_prayagraj_sangam_tents_07',
    googleRating: 4.9,
    googleReviewCount: 110,
    googleReviews: [
      {
        author: 'Vikram Singhal',
        rating: 5,
        text: 'Unbelievable comfort right in the mela grounds. The hot water and room heater were life savers during January cold waves.',
        date: 'January 2026',
      },
    ],
    verificationStatus: 'verified',
    ownerVerified: true,
    propertyVerified: true,
    locationVerified: true,
    photoVerified: true,
    trustScore: 98,
    lastVerifiedAt: new Date('2026-08-25'),
    rules: ['24/7 security check at sector gate', 'Buffet dining included'],
    contactPhone: '+91 99350 88776',
    source: { file: 'prayagraj_verified_directory.json', originalId: 'PRY_003' },
    isDemo: true,
    isActive: true,
  },
];
